{% set name = "pixell" %}
{% set version = "0.27.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pixell-{{ version }}.tar.gz
  sha256: 1c77ff57ffb2a0ff318de9b3c0e066d2ff404ee29b412a3ff5df576df76b78f8
  patches:
    - qsort_const.patch

build:
  skip: true  # [py<39 or win]
  script: {{ PYTHON }} -m pip install . -vv --no-deps .
  script_env:
    - FFLAGS=-Wno-tabs -Wno-conversion -Wno-unused-variable
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - {{ stdlib("c") }}
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
    - automake
    - autoconf
    - m4
    - libtool
    - make
  host:
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
    - libopenblas * *openmp*
    - libblas * *openblas
    - python
    - meson-python
    - cython
    - numpy <2.0
    - scipy
    - astropy
    - healpy
    - matplotlib-base
    - pyyaml
    - h5py
    - pillow
    - pyfftw
    - libxcrypt1  # [linux]
    - pip
  run:
    - llvm-openmp  # [osx]
    - libopenblas * *openmp*
    - libblas * *openblas
    - {{ pin_compatible("scipy") }}
    - matplotlib-base
    - python
    - pip
    - coveralls
    - cython
    - ducc0
    - numba
    - pytest
    - pytest-cov
    - astropy
    - healpy
    - pyyaml
    - h5py
    - pillow !=10.4.0,>=5.3.0
    - pyfftw


test:
  commands:
    - pip check
  imports:
    - pixell

about:
  home: https://github.com/simonsobs/pixell/tree/master
  summary: A rectangular pixel map manipulation and harmonic analysis library derived from Sigurd Naess' enlib.
  description: |
    pixell is a library for loading, manipulating and analyzing maps stored in 
    rectangular pixelization. It is mainly targeted for use with maps of the 
    sky (e.g. CMB intensity and polarization maps, stacks of 21 cm intensity 
    maps, binned galaxy positions or shear) in cylindrical projection, but 
    its core functionality is more general. It extends numpy’s ndarray to an 
    ndmap class that associates a World Coordinate System (WCS) with a numpy 
    array. It includes tools for Fourier transforms (through numpy or pyfft) 
    and spherical harmonic transforms (through ducc0) of such maps and tools 
    for visualization (through the Python Image Library).
  license: BSD-3-Clause
  license_file: LICENSE


extra:
  recipe-maintainers:
    - JBorrow
    - msyriac
    - iparask
